Add file to convert raw data into input
bdh-team-12/sleep-predictions-through-deep-learning pull request #10
Opened 2019-04-11 00:53 UTC by BobRiley1

I was told I need to do this for GitHub to allow my code into the Develop branch.  

This is the file that converts raw data into Input for the Scala file (similar to HW4)

just reads the .csv files, not included because they're private access.

2019-04-12 03:25 UTC, macnb9 requested changes
Could you break this out into more modular functions and wrap an example of usage in a `if __name__ == "__main__":` block at the end of the file? That way we can keep our source code clean and readable by other researchers

2019-04-13 18:56 UTC, dkapp7 commented
That's too bad you made this file. I literally already made a python file last week that did the same thing. I had mentioned it in the PR.

2019-04-18 02:43 UTC, dkapp7 approved these changes

2019-04-19 19:07 UTC, macnb9 approved these changes

2019-04-21 17:48 UTC, blakemacnair commented
@dkapp7 @BobRiley1 is this good to merge or has this been deprecated by #7 ?

2019-04-23 02:39 UTC, merged