Add files via upload
bdh-team-12/sleep-predictions-through-deep-learning pull request #13
Opened 2019-04-14 19:55 UTC by rongncao

you need change shhs_base_dir to your local drive
also this code uses utils and plot we developed for hw5

2019-04-18 02:43 UTC, dkapp7 submitted a review, later dismissed

2019-04-18 02:43 UTC, dkapp7 commented on SHHS model - RNN LSTM RF.py
> +class MyRNN(nn.Module):
is this RNN optimized?

2019-04-21 17:52 UTC, blakemacnair commented
@rongncao can you move the added files into an existing or new directory to keep them organized by purpose within the project structure?

2019-04-21 17:54 UTC, macnb9 requested changes
Repeat of my question to more explicitly block: can you move the added files into an existing or new directory to keep them organized by purpose within the project structure?

2019-04-21 23:08 UTC, rongncao commented
will do

On Sun, Apr 21, 2019 at 12:54 PM Blake Macnair <notifications@github.com>
wrote:

> *@blakemacnair* requested changes on this pull request.
>
> Repeat of my question to more explicitly block: can you move the added
> files into an existing or new directory to keep them organized by purpose
> within the project structure?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/bdh-team-12/sleep-predictions-through-deep-learning/pull/13#pullrequestreview-228921391>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ALMDY33CBBK7XR6IFHLEY33PRSS4XANCNFSM4HF3IF3Q>
> .
>

2019-04-22 02:53 UTC, closed without merging